### ISSUE TITLE
`useEmitAsProps` triggers TS2589 ("Type instantiation is excessively deep") since v2.10.0

### ISSUE THREAD

**Issue by dabutta** [unovue/reka-ui#2766]
## Summary

Since **v2.10.0** — specifically PR [#2643](https://github.com/unovue/reka-ui/pull/2643) *"Enhance type inference for useEmitAsProps and useForwardPropsEmits"* — calling `useEmitAsProps` with a **type-only** `defineEmits<{ ... }>()` declaration makes `vue-tsc` fail with:

```
error TS2589: Type instantiation is excessively deep and possibly infinite.
```

The new precise return type (`on${Capitalize<EventName>}` keys, derived via a template-literal mapped type) is the trigger: resolving it over the emit signature exceeds TypeScript's instantiation-depth limit. Runtime behaviour is unaffected — this is type-check only.

## Environment

| Package      | Version |
| ------------ | ------- |
| `reka-ui`    | 2.10.0  |
| `vue`        | 3.5.38  |
| `vue-tsc`    | 3.3.5   |
| `typescript` | 6.0.3   |

## Minimal reproduction

```vue
<!-- Repro.vue -->
<script setup lang="ts">
import { useEmitAsProps } from 'reka-ui';

// Type-only emit declaration — this is what triggers TS2589.
const emits = defineEmits<{ submit: [void] }>();
const forwarded = useEmitAsProps(emits);
</script>

<template>
    <form v-bind="forwarded"></form>
</template>
```

```bash
npx vue-tsc --noEmit
# Repro.vue(6,19): error TS2589: Type instantiation is excessively deep and possibly infinite.
```

## Expected vs. actual

- **Expected:** `useEmitAsProps(emits)` type-checks and returns `{ onSubmit: ... }`.
- **Actual:** `vue-tsc` aborts the type with TS2589.

## Notes on the trigger

- It reproduces with **typed** emits (`defineEmits<{ submit: [void] }>()`).
- It does **not** reproduce with the **array** form (`defineEmits(['submit'])`), which infers `Name = string` and keeps the mapped type cheap. This points at the per-event-name `Capitalize<...>` template-literal mapping over the typed-emit union as the cost center introduced by #2643.

## Workaround (for other affected users)

Cast the **function** (not its result) to a loose signature so TS never instantiates the precise return type:

```ts
import { useEmitAsProps } from 'reka-ui';

export function forwardEmit(emit: (...args: any[]) => void): Record<string, (...args: any[]) => void> {
    return (useEmitAsProps as (e: unknown) => Record<string, (...args: any[]) => void>)(emit);
}
```

Casting the result instead (`useEmitAsProps(emits) as ...`) does **not** help — TS still computes the call's return type before applying the assertion.

## Suggested direction

Bound the recursion / instantiation depth in the `EmitAsProps` (and `useForwardPropsEmits`) return types so precise inference is retained without exceeding TypeScript's depth limit — e.g. simplify the template-literal key mapping, or fall back to a widened record type when the emit type is not a finite string-literal union.

**Comment by dabutta** [comment]
removing `void` helped 🙈
